initial commit for mrtur

diff --git a/_archidroid/auto/system/etc/init.d/98ArchiDroid_RunOnce b/_archidroid/auto/system/etc/init.d/98ArchiDroid_RunOnce
--- a/_archidroid/auto/system/etc/init.d/98ArchiDroid_RunOnce
+++ b/_archidroid/auto/system/etc/init.d/98ArchiDroid_RunOnce
@@ -9,7 +9,6 @@
 # Initial variables, you should NOT change them unless you know what you're doing
 AD="/data/media/0/ArchiDroid"
 LOG="$AD/RunOnce.log" # "/dev/null" is no verbose
-FORCE=0 # We don't want to force anything in update mode
 
 # Redirect stderr to our log, just in case something bad happen
 #exec 1>$LOG # Use "exec 1>>$LOG" for append
@@ -110,14 +109,25 @@ else
 	ADBANNER=0
 fi
 
+# Don't force install mode, unless FORCE file exists
+if [ -e $AD/FORCE ]; then
+	echo "WARNING: Forcing Install mode, even if Update mode found!" >> $LOG
+	FORCE=1
+else
+	echo "INFO: Not forcing Install mode if Update mode found" >> $LOG
+	FORCE=0
+fi
+
 # We want some sqlite3 updates and settings but only if INSTALL mode is enabled
 if [ -e $AD/INSTALL ] || [ $FORCE -eq 1 ]; then
 	echo "INFO: Install mode detected, I'm either after full wipe or forced to think so. Turning on ADMANY and DBUPDATE" >> $LOG
 	if [ -d $AD/FIRSTBOOT/DATA ]; then
 		cd $AD/FIRSTBOOT/DATA
 		ADMANY=`ls | wc -l`
-		echo "INFO: I found $ADMANY folders which need merging (data)" >> $LOG
+	else
+		ADMANY=0
 	fi
+	echo "INFO: I found $ADMANY folders which need merging (data)" >> $LOG
 	DBUPDATE=1
 	ADRELOAD=1
 elif [ -e $AD/UPDATE ]; then
@@ -163,7 +173,11 @@ while ! pgrep com.android && [ $LOOP -lt 150 ] ; do
 		if [ -e /data/data/com.android.providers.settings/databases/settings.db ]; then
 			echo "INFO: Android created settings.db for me, how cute! Performing DBUPDATE" >> $LOG
 			DBUPDATE secure advanced_reboot 1
+			
+			# Requires SlimBean's Dark Droid
 			DBUPDATE secure ui_inverted_mode 2
+			DBUPDATE secure kill_app_longpress_back 1
+			
 			DBUPDATE global transition_animation_scale 0.5
 			DBUPDATE global animator_duration_scale 0.5
 			DBUPDATE global window_animation_scale 0.5
@@ -176,6 +190,26 @@ while ! pgrep com.android && [ $LOOP -lt 150 ] ; do
 			DBUPDATE system statusbar_clock_date_format 'MMM dd'
 			DBUPDATE system status_bar_traffic 0
 			DBUPDATE system button_backlight_timeout 1000
+			DBUPDATE system recents_clear_all_on_right 1
+			DBUPDATE system recents_ram_bar_mode 3
+			
+			# Reguires AOKP Custom Animations
+			DBUPDATE system animation_controls_no_override 1
+			DBUPDATE system animation_controls_duration 34
+			DBUPDATE system task_open 8
+			DBUPDATE system task_close 8
+			DBUPDATE system task_to_front 8
+			DBUPDATE system task_to_back 8
+			DBUPDATE system wallpaper_open 8
+			DBUPDATE system wallpaper_close 8
+			DBUPDATE system wallpaper_intra_open 8
+			DBUPDATE system wallpaper_intra_close 8
+			DBUPDATE system activity_open 8
+			DBUPDATE system activity_close 8
+			
+			# Requires ListView Animations
+			DBUPDATE system listview_animation 4
+			DBUPDATE system listview_interpolator 5
 			
 			# And don't execute twice
 			echo "INFO: Finished DBUPDATE" >> $LOG
@@ -189,15 +223,24 @@ while ! pgrep com.android && [ $LOOP -lt 150 ] ; do
 		for FOLDER in * ; do
 			if [ -d /data/data/$FOLDER ]; then
 				echo "INFO: I'm merging $FOLDER, called by ADMANY" >> $LOG
-				mv $FOLDER/* /data/data/$FOLDER
-
-				# Let's set basic permissions because ArchiDroid_Permfix will fix it anyway really soon
 				ADOWNER=`ls -ld /data/data/$FOLDER | awk '{print $3}'`
-				busybox chown -hR $ADOWNER.$ADOWNER /data/data/$FOLDER
-				busybox chmod -R 755 /data/data/$FOLDER
+				mkdir /data/data/$FOLDER/_ADTEMP
+				cp -R $FOLDER/* /data/data/$FOLDER/_ADTEMP/
+				
+				# I hate using implementations like this one, our shell is very limited. Forgive me
+				echo "cd /data/data/$FOLDER/_ADTEMP && cp -R * .." | su "$ADOWNER"
+				
+				if [ $? -eq 0 ]; then
+					echo "INFO: It looks like everything ended successfully on $FOLDER" >> $LOG
+				else
+					echo "ERROR: su failed on $FOLDER, falling back to dirty chmod 777, please investigate" >> $LOG
+					cd /data/data/$FOLDER/_ADTEMP && cp -R * .. && cd $AD/FIRSTBOOT/DATA
+					busybox chmod -R 777 /data/data/$FOLDER/*
+				fi
 
 				# And we're done!
 				rm -Rf $FOLDER
+				rm -Rf /data/data/$FOLDER/_ADTEMP
 				ADOWNER=""
 				ADMANY=`ls | wc -l`
 				echo "INFO: $ADMANY to go" >> $LOG
@@ -218,7 +261,7 @@ else
 fi
 
 # Now that is checked, let's just wait another tiny little bit
-sleep 5
+sleep 8
 
 # If we have any more runonce scripts then it's the right place for that
 
@@ -238,6 +281,7 @@ fi
 # ArchiDroid has sysro/sysrw support, change that to remount system rw if needed
 rm -f $AD/INSTALL
 rm -f $AD/UPDATE
+rm -f $AD/FORCE
 rm -Rf $AD/FIRSTBOOT
 rm -Rf /data/media/0/vrtheme-backup
 sysrw
@@ -252,11 +296,15 @@ fi
 
 # Execute hot reboot if we need it
 if [ $ADRELOAD -eq 1 ]; then
-	echo "INFO: Hot reboot required, I'm killing system_server right now" >> $LOG
+	echo "INFO: Hot reboot required, I'm killing system_server right now." >> $LOG
+	# Finish
+	echo "INFO: ArchiDroid RunOnce finished" >> $LOG
+	echo "`date`" >> $LOG
+	#reboot
 	killall system_server
+else
+	# Finish
+	echo "INFO: ArchiDroid RunOnce finished" >> $LOG
+	echo "`date`" >> $LOG
 fi
-
-# Finish
-echo "INFO: ArchiDroid RunOnce finished" >> $LOG
-echo "`date`" >> $LOG
 exit 0
