EXPERIMENTAL: debian, github

diff --git a/_mrturdroid/auto/system/bin/adflash b/_mrturdroid/auto/system/bin/adflash
--- a/_mrturdroid/auto/system/bin/adflash
+++ b/_mrturdroid/auto/system/bin/adflash
@@ -1,12 +1,24 @@
 #!/system/bin/sh
 
 VERSION=""
-MODE="git"
 TEMP=""
-AD="/data/media/0/MrturDroid"
 NOZIP=0
 
+if [ -d /storage/sdcard1/MrturDroid ]; then
+	AD="/storage/sdcard1/MrturDroid"
+elif [ -d /storage/extSdCard/MrturDroid ]; then
+	AD="/storage/extSdCard/MrturDroid"
+else
+	AD="/data/media/0/MrturDroid"
+fi
+if [ -d $AD/GitHub ]; then
+	MODE="git"
+else
+	MODE="direct"
+fi
+
 echo "Welcome to MrturDroid Command Line Flasher!"
+echo "Detected MrturDroid in $AD"
 echo "Checking access to $AD"
 mkdir -p $AD/tmp
 cd $AD/tmp && rm -f test && touch test && rm -f test
@@ -31,11 +43,21 @@ if [ $# -eq 0 ]; then
 	echo ""
 	echo "You may specify any extra options here separated by a whitespace. Eventually you can just skip this question and apply defaults"
 	echo ""
-	echo "git			[Default] Sets up local git repository, which gives you delta upgrades and bandwidth saving"
+	echo "MrturDroid will prioritize git mode if MrturDroid github repository already exists on your device and eventually fall back to direct, you can override this here"
+	echo "Currently using mode: $MODE. If you're satisfied with this mode you can just skip this question"
+	echo "git			Sets up local git repository, which gives you delta upgrades and bandwidth saving"
 	echo "direct		Downloads targeted branch as .zip file directly from github"
 	echo ""
+	echo "MrturDroid will prioritize extsd if it contains MrturDroid folder and eventually fall back to intsd, you can override this here"
+	echo "Currently using MrturDroid in: $AD. If you're satisfied with this path you can just skip this question"
+	echo "extsd			Use external sd card (/storage/sdcard1 /storage/extSdCard)"
+	echo "intsd			Use internal sd card (/data/media/0)"
+	echo ""
+	echo "Other selectable options"
 	echo "nozip			Shows changelog and changes only"
 	echo ""
+	echo ""
+	echo "Example: git extsd"
 	echo -n "Your extra options: "
 	read EXTRA
 else
@@ -69,13 +91,53 @@ for arg in $EXTRA; do
 		"nozip")
 			NOZIP=1
 			;;
+		"intsd")
+			if [ "$AD" != "/data/media/0/MrturDroid" ]; then
+				echo "Changing path to internal sd!"
+				AD="/data/media/0/MrturDroid"
+				mkdir -p $AD/tmp
+				cd $AD/tmp && rm -f test && touch test && rm -f test
+				CHECK1=$?
+				if [ $CHECK1 -ne 0 ]; then
+					echo "Sorry, access test failed. Make sure that $AD/tmp is not being owned by root or give me root access"
+					exit 1
+				else
+					echo "Access test passed, we're ready to go!"
+				fi
+			fi
+			;;
+		"extsd")
+			if [ "$AD" == "/data/media/0/MrturDroid" ]; then
+				echo "Changing path to external sd!"
+				if [ -e /storage/sdcard1 ]; then
+					AD="/storage/sdcard1/MrturDroid"
+				elif [ -e /storage/extSdCard ]; then
+					AD="/storage/extSdCard/MrturDroid"
+				fi
+
+				if [ "$AD" != "/data/media/0/MrturDroid" ]; then
+					mkdir -p $AD/tmp
+					cd $AD/tmp && rm -f test && touch test && rm -f test
+					CHECK1=$?
+					if [ $CHECK1 -ne 0 ]; then
+						echo "Sorry, access test failed. Make sure that $AD/tmp is not being owned by root or give me root access"
+						exit 1
+					else
+						echo "Access test passed, we're ready to go!"
+					fi
+				else
+					echo "Sorry, could not detect any valid path to use"
+					echo "You selected extsd, but I failed to use it so I'm aborting here"
+					exit 1
+				fi
+			fi
+			;;
 		*)
 			continue
 	esac
 done
-if [ "$MODE" == "direct" ]; then
-	cd $AD/tmp
-	echo ""
+
+echo ""
 	echo "Testing your internet connection..."
 	curl google.com > /dev/null 2>&1
 	CHECK=$?
@@ -84,9 +146,13 @@ if [ "$MODE" == "direct" ]; then
 		echo "Sorry but I can't let you pass, either you don't have a valid connection with the internet or required components aren't working properly"
 		exit 1
 	else
-		echo "Test passed successfully!"
+	echo "Internet test passed successfully!"
 		echo ""
 	fi
+
+if [ "$MODE" == "direct" ]; then
+	mkdir -p $AD/tmp
+	cd $AD/tmp
 	echo "CHANGELOG START"
 	echo ""
 	curl -kSs https://raw.github.com/mrtur/MrturDroid/$VERSION/META-INF/com/google/android/aroma/_changelog.txt
@@ -137,11 +203,19 @@ if [ "$MODE" == "direct" ]; then
 		exit 1
 	fi
 else
+	mkdir -p $AD/GitHub
+	echo "CHANGELOG START"
+	echo ""
+	curl -kSs https://raw.github.com/mrtur/MrturDroid/$VERSION/META-INF/com/google/android/aroma/_changelog.txt
+	echo ""
+	echo ""
+	echo "CHANGELOG EOF"
+	echo ""
 	echo "Booting pocket debian..."
 	adlinux "default"
 	
 	echo "Setting up git repository..."
-	debian "cmd" "cd $AD/GitHub && bash github.sh $VERSION"
+	debian "cmd" "cd $AD/GitHub && adgithub $VERSION"
 	
 	# Expect that repo is ready
 	cd $AD/GitHub/$VERSION
@@ -168,7 +242,7 @@ mv MrturDroid_$VERSION.zip $AD/MrturDroid_$VERSION.zip
 echo "Done, you can find your flashable rom in $AD/MrturDroid_$VERSION.zip"
 
 if [ "$MODE" == "direct" ]; then
-	cd $AD/tmp && rm -rf *
+	rm -rf $AD/tmp
 fi
 
 echo ""
